### ISSUE TITLE
[BUG] Prefix in command auto fill

### ISSUE THREAD

**Issue by SkyLord-103** [eclipseisoffline/customname#2]
When the mod is active the prefixes work as intended but the prefixes appear in command auto fills breaking the player's actual name.
If the name is too long it can cut off parts as well.

![image](https://github.com/eclipseisoffline/customname/assets/76186026/fe01228c-e8b3-424c-97a4-cef0224cd0ae)

I'm running a 1.20.4 fabric server, loader version 0.15.11

I'm unsure if this is unintended behavior or not.
Thanks!

**Comment by eclipseisoffline** [comment]
Hm, that's not supposed to happen. Can you send the mod list on your server?

Does the issue happen with all commands, or only specific ones?

**Comment by SkyLord-103** [comment]
It seems a lot of commands use the prefix, mostly vanilla commands.
Except for Banhammer's commands.

These are the mods that are currently being used https://modrinth.com/collection/LzS7b3jH
*Please let me know if you need the list in some other format*

I tested these commands
```
Voice chat
/voicechat test

Vanilla commands
/tp
/teleport
/tellraw
/tell
/kill
/xp set
/damage
/spectate
/minecraft:ban
/minecraft:kick

Essential Commands
/home tp_other
/extinguish, My user name appears twice one with the prefix and one without
```

**Comment by eclipseisoffline** [comment]
Thank you! This should definitely not happen. I'm pretty busy tomorrow but I will do some testing on Friday and I'll try to implement a fix during the weekend.

**Comment by SkyLord-103** [comment]
I just tried joining with a vanilla client and a no mod fabric client and I still have the issue. Strange.
I will try and update the server's mods and test again myself and with a friend.

If nothing works on my side and since you aren't able to replicate the issue I may just have to live with it.
Thanks for the help!

**Comment by eclipseisoffline** [comment]
Could you possibly send over a ZIP file of your server mods folder? Maybe I'm able to reproduce it that way

**Comment by SkyLord-103** [comment]
Apologies for the late reply. I tested with a friend and the issue still appears which sucks.
And sure, here are the [mods and config folders](https://drive.google.com/file/d/1G1ZLb0Rq5EixoZoy-mvCduqG7C-x1qnP/view?usp=drive_link)

**Comment by eclipseisoffline** [comment]
Thank you! It's unfortunate that the issue remains. I'll try to reproduce it using these options tomorrow and hopefully find the cause of the issue.

**Comment by eclipseisoffline** [comment]
Seems like access to the drive link you sent is denied

**Comment by SkyLord-103** [comment]
Oops I thought I made it open
Try this [one](https://drive.google.com/file/d/1G1ZLb0Rq5EixoZoy-mvCduqG7C-x1qnP/view?usp=drivesdk)

**Comment by eclipseisoffline** [comment]
Works, thank you

**Comment by eclipseisoffline** [comment]
Hi, I have reproduced the issue and identified what causes it!
In your essential commands configuration, you have the `nickname_above_head` option enabled. Simply disabling this option should fix the issue.

If you're interested in a technical explanation, the `nickname_above_head` option is implemented by sending the nicknames of players as their literal player names to the client. This causes the client to show the nicknames above the player heads as if they were their literal names, but also causes the client to list these nicknames in the player suggestions in commands, since the client thinks these are the real player names.

There might be a fix available, but it probably won't be an easy one to implement. It's easier to just disable the option, since it doesn't cause a huge inconvenience. The issue has already been reported on the essential commands repo ([here](https://github.com/John-Paul-R/Essential-Commands/issues/216)).

**Comment by SkyLord-103** [comment]
Thats great!! *huh darn I didn't know thats how names are transfered lol*
I'll update essentials when I have access to the server and then celebrate!
Thank you very much for the help!
